### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SnarfW** [JustCarmen/webtrees-simple-media-display#2]
First of all thank you very much for making this module available. I did download and installed the module, unfortunately I do receive an error:

Call to undefined method Fisharebest\Webtrees\Registry::idFactory() …/modules_v4/jc-media-display/resources/views/fact-gedcom-fields.phtml:60
#0 …/app/View.php(183): include()
#1 …/app/View.php(278): Fisharebest\Webtrees\View->render()
#2 …/app/Helpers/functions.php(145): Fisharebest\Webtrees\View::make()
#3 …/resources/views/modules/sources_tab/tab.phtml(52): view()

I am still running on Webtrees 2.1.4, should I upgrade to 2.1.6 to use this module?

**Comment by SnarfW** [comment]
I just upgrade to the latest release of Webtrees, in 2.1.6 your module is working without errors.

Once again thank you for desigining this module
